// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"p-2 font-mono\"><pre class=\"font-mono whitespace-pre leading-none text-transparent bg-clip-text bg-gradient-to-r from-cyan-300 via-yellow-500 to-emerald-300\"><br>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(` ____  __.          .__         ___________                     
|    |/ _|_______  _|__| ____   \__    ___/___________    ____  
|      <_/ __ \  \/ /  |/    \    |    |  \_  __ \__  \  /    \ 
|    |  \  ___/\   /|  |   |  \   |    |   |  | \// __ \|   |  \
|____|__ \___  >\_/ |__|___|  /   |____|   |__|  (____  /___|  /
        \/   \/             \/                        \/     \/ `)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/partials/home.templ`, Line: 13, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre><h1 class=\"text-gray-300 \"><br>Software Developer </h1><blockquote class=\"text-gray-500\" cite=\"https://www.goodreads.com/quotes/515816-that-s-all-it-took-to-solve-problems---just-sense\">\"That's all it took to solve problems - Just sense.\" <br>└ Gary Paulsen, Hatchet</blockquote></section><section class=\"p-2\"><h1 class=\"text-gray-300 font-mono\"><br>About Me</h1><p class=\"text-gray-500 font-mono\">I’m a Full Stack Developer building scalable, data-driven applications using .NET, Go, Python, PostgreSQL/SQL Server, and React/Next.js. I’m curious, detail-oriented, and thrive on solving hard problems with clean, efficient solutions.<br><br>Outside of coding, I’m passionate about ortholinear keyboards, photography, guitar, and travel. I'm always tinkering, creating, or exploring something new.<br><br></p><a href=\"https://github.com/5PK\" class=\"font-mono text-gray-300\">github.com/5PK</a><br><a href=\"https://www.linkedin.com/in/5PK\" class=\"font-mono text-gray-300\">linkedin.com/in/5PK</a></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
