// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Terminal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-black w-full h-full flex justify-center items-center\"><div class=\"border-gray-300 border-2 border-t-16 w-200 h-230 flex flex-col justify-between\"><!-- Terminal Output Area --><div id=\"terminal-output\" class=\"flex-1 overflow-y-auto min-h-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Home().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><!-- Command Input --><form hx-post=\"/terminal/command\" hx-target=\"#terminal-output\" hx-swap=\"beforeend\" hx-trigger=\"submit\" class=\"flex gap-2\" hx-on::after-request=\"document.getElementById('command-input').value=''\"><span class=\"font-mono text-green-400 pl-2\">kevin@portfolio:~$</span> <input type=\"text\" name=\"command\" id=\"command-input\" class=\"font-mono flex-1 bg-transparent border-none outline-none text-gray-300 placeholder-gray-800\" placeholder=\"type 'help' for commands\" autocomplete=\"off\" autofocus></form></div></div><script>\n\t\t  document.body.addEventListener(\"htmx:afterSwap\", (e) => {\n\t\t\tif (e.detail.target.id === \"terminal-output\") {\n\t\t\t  e.detail.target.scrollTop = e.detail.target.scrollHeight;\n\t\t\t}\n\t\t  });\n\t\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
