// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Terminal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-black w-full h-full flex md:justify-center md:items-center\"><div id=\"terminal-container\" class=\"border-gray-300 border-2 border-t-16 w-full h-full lg:w-200 lg:h-230 flex flex-col justify-between\"><!-- Terminal Output Area --><div id=\"terminal-output\" class=\"flex-1 overflow-y-auto min-h-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Home().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><!-- Command Input --><form hx-post=\"/terminal/command\" hx-target=\"#terminal-output\" hx-swap=\"beforeend\" hx-trigger=\"submit\" class=\"flex gap-2\" hx-on::after-request=\"document.getElementById('command-input').value=''\"><span class=\"text-2xl lg:text-base font-mono text-green-400 pl-2\">kevin@portfolio:~$</span> <input type=\"text\" name=\"command\" id=\"command-input\" class=\"text-2xl lg:text-base font-mono flex-1 bg-transparent border-none outline-none text-gray-300 placeholder-gray-800\" placeholder=\"type 'help' for commands\" autocomplete=\"off\"></form></div></div><script>\n\t\t  // Only autofocus on non-mobile devices\n\t\t  if (!(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent))) {\n\t\t\tdocument.getElementById('command-input').focus();\n\t\t  }\n\n\t\t  document.body.addEventListener(\"htmx:afterSwap\", (e) => {\n\t\t\tif (e.detail.target.id === \"terminal-output\") {\n\t\t\t  const target = e.detail.target;\n\n\t\t\t  // Check if there are images that need to load\n\t\t\t  const images = target.querySelectorAll('img');\n\t\t\t  if (images.length > 0) {\n\t\t\t\t// Wait for all images to load before scrolling\n\t\t\t\tlet loadedCount = 0;\n\t\t\t\tconst totalImages = images.length;\n\n\t\t\t\tconst scrollWhenReady = () => {\n\t\t\t\t  loadedCount++;\n\t\t\t\t  if (loadedCount === totalImages) {\n\t\t\t\t\ttarget.scrollTop = target.scrollHeight;\n\t\t\t\t  }\n\t\t\t\t};\n\n\t\t\t\timages.forEach(img => {\n\t\t\t\t  if (img.complete) {\n\t\t\t\t\tscrollWhenReady();\n\t\t\t\t  } else {\n\t\t\t\t\timg.addEventListener('load', scrollWhenReady);\n\t\t\t\t\timg.addEventListener('error', scrollWhenReady); // Handle broken images\n\t\t\t\t  }\n\t\t\t\t});\n\t\t\t  } else {\n\t\t\t\t// No images, scroll immediately\n\t\t\t\ttarget.scrollTop = target.scrollHeight;\n\t\t\t  }\n\t\t\t}\n\t\t  });\n\t\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
